# [LAB 07] 3. 단일표본 T-Test
## #연습문제 - 빵집의 양심

In [1]:
from hossam import load_data
from helpers import my_stats

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.19

In [2]:
df=load_data('bread')
df.head()

📚 매일 아침 동네 빵집에서 식빵을 구입해 무게를 기록한 데이터

    무게
0  482
1  479
2  485
3  474
4  479

- 빵의 평균무게가 500g과 차이가 있는지 확인
- 귀무가설 : 빵의 평균무게가 500g과 차이가 없다.
- 대립가설 : 빵의 평균무게가 500g과 차이가 있다.

In [3]:
my_stats.test_1sample(df, column='무게', popmean=500)

                               statistic  p-value  significant   result
test              alternative
One-sample t-test two-sided      -37.524    0.000         True    차이 있음
                  less           -37.524    0.000         True  μ₀보다 작음
                  greater        -37.524    1.000        False     차이없음

- One-sample t-test 양측검정 결과 t값은 -37.574, p-value는 0으로 나타났다. p<0.05이므로 귀무가설을 기각하고 대립가설을 채택한다. 이는 빵의 평균무게가 500g과 차이가 있다는 것을 의미한다.
- 좌측 단측검정 결과 p-value는 0으로 나타났다. p<0.05이므로 귀무가설을 기각하고 대립가설을 채택한다. 즉, 빵의 평균무게가 500g보다 작다.
- 우측 단측검정 결과 p-value는 1로 나타났다. p>=1이므로 귀무가설을 채택한다. 즉, 빵의 평균무게는 500g보다 크지 않다.
- 빵의 평균무게가 500g보다 작다는 것을 확인할 수 있다.