# [LAB 07] 2. 가설검정의 이해
## #연습문제 - 아이스크림 발주넣기

In [2]:
from hossam import load_data
from helpers import my_plot, my_stats
from pandas import melt, DataFrame

# 가설 검정의 가정에 필요한 패키지
from scipy.stats import shapiro, normaltest, bartlett, levene

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.19

In [6]:
origin = load_data('icecream')
origin.head()

📚 기온과 아이스크림 판매량을 기록한 가상의 데이터 (메타데이터,인덱스 없음)

   기온  판매량
0  23  431
1  36  593
2  30  512
3  25  474
4  26  476

#### 문제 1. 유의수준 0.05에서 정규성 검정 결과를 해석하고, 기온과 판매량이 정규성 가정을 만족하는지 답하시오.
- 기온과 판매량은 정규성을 만족함

In [4]:
my_stats.test_assumptions(origin, columns=['기온', '판매량'])

                test  statistic  p-value  result
field
기온        normaltest      2.745    0.253    True
판매량       normaltest      0.715    0.700    True
Bartlett   equal_var     44.148    0.000   False

#### 문제 2. 등분산성 검정을 위해 사용되는 검정방법은?
- Bartlett 검정이 사용됨

#### 문제 3. 두 변수가 등분산 가정을 만족하는가?
- 만족하지 않음. p-value 값이 0.05보다 작은 0이므로 등분산성에 위배됨