# [LAB 09] 3-2. 회귀분석 결과보고 모듈화
#### 연습문제 1 - 골턴의 유산 - 분석결과 보고

In [1]:
# 라이브러리 기본 참조
from hossam import load_data
from helpers import *
from IPython.display import display, Markdown

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.21

⚠️  'hossam' 패키지의 최신 버전이 출시되었습니다! (설치된 버전: 0.5.21, 최신 버전: 0.5.23)
   최신 버전으로 업데이트하려면 다음 명령어를 실행하세요:
   pip install --upgrade hossam

In [5]:
origin = load_data('father-son')
origin.head()

📚 아버지와 아들의 키를 조사한 데이터 (출처: https://www.kaggle.com/datasets/aungdev/pearson-dataset-heights-of-fathers-and-their-sons)

   fheight  sheight
0   65.049   59.778
1   63.251   63.214
2   64.955   63.342
3   65.752   62.792
4   61.137   64.281

In [6]:
fit = my_ols.fit_model(origin, 'sheight', summary=True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                sheight   R-squared:                       0.251
Model:                            OLS   Adj. R-squared:                  0.251
Method:                 Least Squares   F-statistic:                     361.2
Date:                Wed, 08 Jul 2026   Prob (F-statistic):           1.12e-69
Time:                        13:07:22   Log-Likelihood:                -2488.7
No. Observations:                1078   AIC:                             4981.
Df Residuals:                    1076   BIC:                             4991.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         33.8866      1.832     18.493      0.000      30.291      37.482
fheight        0.5141      0.027     19.006      0.000       0.461       0.567
==============================================================================
Omnibus:                       17.605   Durbin-Watson:                   0.767
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.849
Skew:                          -0.051   Prob(JB):                     2.00e-07
Kurtosis:                       3.822   Cond. No.                     1.67e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.67e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [7]:
# 회귀계수 표
vdf = my_ols.report_variables(fit, origin)
display(vdf)

# 모형적합도 보고 (로그변환 없음)
display(Markdown(my_ols.report_fitness(fit)))

# 독립변수 보고(로그변환 없음)
display(Markdown(my_ols.report_variables_text(fit)))

      종속변수     독립변수     B  표준오차     β      t  유의확률    공차   VIF
0  sheight  fheight 0.514 0.027 0.501 19.006 0.000 1.000 1.000

**Note. n = 1078. F(1, 1076) = 361.23, p < 0.001, R² = 0.251, Adj.R² = 0.251, Durbin_Watson = 0.767**

sheight를 종속변수로, fheight(을)를 독립변수로 한 단순선형회귀분석 결과, 모형은 통계적으로 유의하였다.

> F(1, 1076) = 361.23 , p < 0.001, R² = 0.251.

즉, fheight는 sheight의 약 25.13%를 설명하는 것으로 나타났다.

- **fheight**의 회귀계수는 **B = 0.51**으로 나타났으며, 이는 **sheight**에 유의한 요인임을 의미한다. (**t(1076) = 19.01**, **p < .001**) 즉, **fheight가 1 증가**할 때 sheight는 평균적으로 **0.51 증가**하는 것으로 해석된다.

#### 연습문제 2 - 근속년수에 따른 연봉 예측모델 만들기

In [8]:
df = load_data('salary')
df.head()

📚 경력(년차)에 따른 연봉(USD) 데이터 (출처: https://www.kaggle.com/datasets/abhishek14398/salary-dataset-simple-linear-regression)

    field            description
--  ---------------  -------------
 0  YearsExperience  경력(년차)
 1  Salary           연봉(USD)

   YearsExperience    Salary
0            1.200 39344.000
1            1.400 46206.000
2            1.600 37732.000
3            2.100 43526.000
4            2.300 39892.000